env:
  node: true
  es6: true
extends:
  - airbnb-base
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
plugins:
  - "@typescript-eslint"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
rules:
  generator-star-spacing: off
  no-debugger: off
  no-unused-vars: off
  import/extensions: off
  import/prefer-default-export: off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-this-alias": off
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
overrides:
  - files:
    - "./**/*.ts"
    - "./**/*.js"
