bot:
  help:
    h1: '명령어 목록'
    h2: '아래의 명령어를 사용할 수 있습니다.'
    footer: '`[[0]]도움말 [명령어]`를 입력해서 각 명령어에 대한 도움말을 볼 수 있습니다.'
    message: ' '

module:
  dialog:
    code_fail: '대화 코드를 찾을 수 없습니다.'
    init_fail: '대화 모듈 초기화 중 오류가 발생했습니다.'
    chk_fail: '대답을 확인하던 중 오류가 발생했습니다.'
    chk_log: '대답을 이해하지는 못했지만 왜 이해하지 못했는지 내부 기록을 남겼습니다.\n반복해서 오류가 발생하면 응답 시간(`[[0]]`초) 초과를 기다린 다음, 오류 코드 `0x[[1]]`을 [[2]]님께 전달해주세요.\n불편을 끼쳐드려 죄송합니다.'
    close: '[[0]] 님, `[[1]]`초 간 응답이 없어 대화를 종료합니다.'

system:
  version: 'Version [[0]]'
  ping:
    bad: '지연 시간이 큽니다.'
    good: '지연 시간이 작습니다.'
    message: '현재 평균 지연 시간은 **[[0]]ms** 입니다.'
  help:
    no_content: '이 명령어는 따로 도움말이 없습니다.'
    no_command: '`[[0]]`는 없는 명령어입니다.'
    only_dm: '이 명령어는 DM 채널에서만 사용할 수 있습니다.'
    not_dm: 'DM 채널에서는 이 명령어를 사용할 수 없습니다.'
    only_lndrAdmin: '이 명령어는 리엔더 관리자만 사용할 수 있습니다.'
    only_guildAdmin: '이 명령어는 디스코드 서버 관리자만 사용할 수 있습니다.'
    some_author: '이 명령어는 특정 멤버만 사용할 수 있습니다.'
    some_channel: '이 명령어는 특정 채널에서만 사용할 수 있습니다.'
    some_guild: '이 명령어는 특정 디스코드 서버에서만 사용할 수 있습니다.'
    need_guildAdmin: '디스코드 서버 관리자 권한이 필요합니다.'
    need_lndrAdmin: '리엔더 관리자 권한이 필요합니다.'
  invite:
    h1: '초대 링크를 안내합니다.'
    h2: '저를 더욱 많은 분들과 만나게 해 주셔서 감사합니다.'
    h3: '초대 링크를 클릭하여 원하는 다른 서버에 추가해주세요.'
    denied: '저는 다른 서버에 초대받을 수 없도록 설정되어 있습니다.\n[[0]] 님께 문의 부탁드립니다.'
  log:
    success: '메시지가 `[[0]]` 번 로그에 저장되었습니다.'
