bot:
  help:
    h1: '<:lndrcircle:590238436758257719>  명령어 목록'
    h2: '리엔더에게 아래의 명령어를 사용할 수 있어요.'
    footer: '`[[0]]도움말 [명령어]`를 입력해서 각 명령어에 대한 도움말을 보실 수 있어요.'
    message: '지휘관님, 가끔은 제게 의지하셔도 괜찮다구요?'

module:
  dialog:
    code_fail: '대화 코드를 찾을 수 없습니다.'
    init_fail: '대화 모듈 초기화 중 오류가 발생했습니다.'
    chk_fail: '대답을 확인하던 중 오류가 발생했습니다.'
    chk_log: '대답을 이해하지는 못했지만 왜 이해하지 못했는지 내부 기록을 남겼습니다.\n반복해서 오류가 발생하면 응답 시간(`[[0]]`초) 초과를 기다린 다음, 오류 코드 `0x[[1]]`을 [[2]]님께 전달해주세요.\n불편을 끼쳐드려 죄송합니다.'
    close: '[[0]] 님, `[[1]]`초 간 응답이 없어 대화를 종료합니다.'

system:
  version: 'Version [[0]]'
